### PR TITLE
Patch to fix linking against QScintilla with XCode8

### PR DESCRIPTION
**Pull request by ceholden**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR adds a patch that fixes issues I've seen when linking against QScintilla 2.9 using XCode. The patch was originally developed by Alan Garny and others, and posted to the QScintilla mailing list in October, 2016. It was used to fix issues building sqlitebrowser, opencor, and was used in Homebrew for the 2.9 release series. It isn't included as a patch in Homebrew for the 2.10+ releases (see [commit for 2.10 update](https://github.com/Homebrew/homebrew-core/commit/c01fb9168a68b2fe3d288cc8255b7b3095d4fca8)), as the relevant sections have been modified, and I suspect it won't be needed.

I was hoping to simply upgrade this recipe to `2.10.8` (as with the other PR), but I can't pull in a version of Qt from conda-forge that uses SIP 4.19 and the 2.10 releases require SIP 4.19.

Here's a [build log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=21603&view=logs) for QGIS that shows the error, which I'll also post below. QGIS builds fine when linking against my local copy of QScintilla (also up on my `ceholden` channel).

<details><summary>QScintilla linking error</summary>

```
FAILED: src/gui/CMakeFiles/qgis_gui.dir/moc_qgscodeeditor.cpp.o 
$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang++  -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0 -DQT_GUI_LIB -DQT_MACEXTRAS_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_POSITIONING_LIB -DQT_PRINTSUPPORT_LIB -DQT_QML_LIB -DQT_QUICKWIDGETS_LIB -DQT_QUICK_LIB -DQT_SERIALPORT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_UITOOLS_LIB -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DWITH_BINDINGS -DWITH_QML -DWITH_QTWEBKIT -Dqgis_gui_EXPORTS -I. -I../src/gui -I../src/gui/symbology -I../src/gui/attributetable -I../src/gui/auth -I../src/gui/editorwidgets -I../src/gui/editorwidgets/core -I../src/gui/effects -I../src/gui/layertree -I../src/gui/layout -I../src/gui/ogr -I../src/gui/processing -I../src/core -I../src/core/annotations -I../src/core/auth -I../src/core/fieldformatter -I../src/core/geometry -I../src/core/layertree -I../src/core/layout -I../src/core/locator -I../src/core/metadata -I../src/core/processing -I../src/core/mesh -I../src/core/providers/memory -I../src/core/raster -I../src/core/scalebar -I../src/core/symbology -I../src/core/effects -I../src/core/expression -I../src/native -Isrc/core -Isrc/gui -Isrc/ui -Isrc/native -I../src/native/mac -isystem $PREFIX/lib/qca-qt5.framework/Headers -isystem $PREFIX/include/qt5keychain -isystem $PREFIX/include -isystem /Library/Frameworks/Mono.framework/Headers -isystem $PREFIX/include/qt -isystem $PREFIX/include/qt/QtCore -isystem $PREFIX/./mkspecs/macx-clang -isystem $PREFIX/include/qt/QtGui -isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Headers -isystem $PREFIX/include/qt/QtMacExtras -isystem $PREFIX/include/qt/QtXml -isystem $PREFIX/include/qt/QtWidgets -isystem $PREFIX/include/qt/QtSvg -isystem $PREFIX/include/qt/QtPrintSupport -isystem $PREFIX/include/qt/QtNetwork -isystem $PREFIX/include/qt/QtWebKitWidgets -isystem $PREFIX/include/qt/QtWebKit -isystem $PREFIX/include/qt/QtSql -isystem $PREFIX/include/qt/QtConcurrent -isystem $PREFIX/include/qt/QtSerialPort -isystem $PREFIX/include/qt/QtPositioning -isystem $PREFIX/include/qt/QtUiTools -isystem $PREFIX/include/qt/QtQuickWidgets -isystem $PREFIX/include/qt/QtQuick -isystem $PREFIX/include/qt/QtQml -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0 -I$PREFIX/include -fdebug-prefix-map==/usr/local/src/conda/- -fdebug-prefix-map==/usr/local/src/conda-prefix -Wall -Wextra -Wno-long-long -Wformat-security -Wno-strict-aliasing -Wno-return-type-c-linkage -Wno-overloaded-virtual -Wimplicit-fallthrough -Qunused-arguments -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.9 -fPIC -fvisibility=hidden   -F$PREFIX/lib  -fPIC -std=gnu++11 -Wno-deprecated-declarations -MD -MT src/gui/CMakeFiles/qgis_gui.dir/moc_qgscodeeditor.cpp.o -MF src/gui/CMakeFiles/qgis_gui.dir/moc_qgscodeeditor.cpp.o.d -o src/gui/CMakeFiles/qgis_gui.dir/moc_qgscodeeditor.cpp.o -c src/gui/moc_qgscodeeditor.cpp
In file included from src/gui/moc_qgscodeeditor.cpp:9:
In file included from src/gui/../../../src/gui/qgscodeeditor.h:22:
In file included from $PREFIX/include/qt/Qsci/qsciapis.h:33:
In file included from $PREFIX/include/qt/Qsci/qsciabstractapis.h:33:
$PREFIX/include/qt/Qsci/qsciscintilla.h:2138:25: error: implicit instantiation of undefined template 'QPointer<QsciLexer>'
    QPointer<QsciLexer> lex;
                        ^
$PREFIX/include/qt/QtCore/qmetatype.h:1333:1: note: template is declared here
QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER(QT_FORWARD_DECLARE_SHARED_POINTER_TYPES_ITER)
^
$PREFIX/include/qt/QtCore/qmetatype.h:209:7: note: expanded from macro 'QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER'
    F(QPointer)
      ^
src/gui/moc_qgscodeeditor.cpp:79:27: error: cannot initialize object parameter of type 'QsciScintilla' with an expression of type 'QgsCodeEditor'
    return QsciScintilla::qt_metacast(_clname);
                          ^~~~~~~~~~~
src/gui/moc_qgscodeeditor.cpp:84:26: error: cannot initialize object parameter of type 'QsciScintilla' with an expression of type 'QgsCodeEditor'
    _id = QsciScintilla::qt_metacall(_c, _id, _a);
                         ^~~~~~~~~~~
3 errors generated.
[3016/4858] Building CXX object src/gui/CMakeFiles/qgis_gui.dir/moc_qgscodeeditorcss.cpp.o
FAILED: src/gui/CMakeFiles/qgis_gui.dir/moc_qgscodeeditorcss.cpp.o 
$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang++  -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0 -DQT_GUI_LIB -DQT_MACEXTRAS_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_POSITIONING_LIB -DQT_PRINTSUPPORT_LIB -DQT_QML_LIB -DQT_QUICKWIDGETS_LIB -DQT_QUICK_LIB -DQT_SERIALPORT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_UITOOLS_LIB -DQT_WEBKITWIDGETS_LIB -DQT_WEBKIT_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DWITH_BINDINGS -DWITH_QML -DWITH_QTWEBKIT -Dqgis_gui_EXPORTS -I. -I../src/gui -I../src/gui/symbology -I../src/gui/attributetable -I../src/gui/auth -I../src/gui/editorwidgets -I../src/gui/editorwidgets/core -I../src/gui/effects -I../src/gui/layertree -I../src/gui/layout -I../src/gui/ogr -I../src/gui/processing -I../src/core -I../src/core/annotations -I../src/core/auth -I../src/core/fieldformatter -I../src/core/geometry -I../src/core/layertree -I../src/core/layout -I../src/core/locator -I../src/core/metadata -I../src/core/processing -I../src/core/mesh -I../src/core/providers/memory -I../src/core/raster -I../src/core/scalebar -I../src/core/symbology -I../src/core/effects -I../src/core/expression -I../src/native -Isrc/core -Isrc/gui -Isrc/ui -Isrc/native -I../src/native/mac -isystem $PREFIX/lib/qca-qt5.framework/Headers -isystem $PREFIX/include/qt5keychain -isystem $PREFIX/include -isystem /Library/Frameworks/Mono.framework/Headers -isystem $PREFIX/include/qt -isystem $PREFIX/include/qt/QtCore -isystem $PREFIX/./mkspecs/macx-clang -isystem $PREFIX/include/qt/QtGui -isystem /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Headers -isystem $PREFIX/include/qt/QtMacExtras -isystem $PREFIX/include/qt/QtXml -isystem $PREFIX/include/qt/QtWidgets -isystem $PREFIX/include/qt/QtSvg -isystem $PREFIX/include/qt/QtPrintSupport -isystem $PREFIX/include/qt/QtNetwork -isystem $PREFIX/include/qt/QtWebKitWidgets -isystem $PREFIX/include/qt/QtWebKit -isystem $PREFIX/include/qt/QtSql -isystem $PREFIX/include/qt/QtConcurrent -isystem $PREFIX/include/qt/QtSerialPort -isystem $PREFIX/include/qt/QtPositioning -isystem $PREFIX/include/qt/QtUiTools -isystem $PREFIX/include/qt/QtQuickWidgets -isystem $PREFIX/include/qt/QtQuick -isystem $PREFIX/include/qt/QtQml -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0 -I$PREFIX/include -fdebug-prefix-map==/usr/local/src/conda/- -fdebug-prefix-map==/usr/local/src/conda-prefix -Wall -Wextra -Wno-long-long -Wformat-security -Wno-strict-aliasing -Wno-return-type-c-linkage -Wno-overloaded-virtual -Wimplicit-fallthrough -Qunused-arguments -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.9 -fPIC -fvisibility=hidden   -F$PREFIX/lib  -fPIC -std=gnu++11 -Wno-deprecated-declarations -MD -MT src/gui/CMakeFiles/qgis_gui.dir/moc_qgscodeeditorcss.cpp.o -MF src/gui/CMakeFiles/qgis_gui.dir/moc_qgscodeeditorcss.cpp.o.d -o src/gui/CMakeFiles/qgis_gui.dir/moc_qgscodeeditorcss.cpp.o -c src/gui/moc_qgscodeeditorcss.cpp
In file included from src/gui/moc_qgscodeeditorcss.cpp:9:
In file included from src/gui/../../../src/gui/qgscodeeditorcss.h:19:
In file included from ../src/gui/qgscodeeditor.h:22:
In file included from $PREFIX/include/qt/Qsci/qsciapis.h:33:
In file included from $PREFIX/include/qt/Qsci/qsciabstractapis.h:33:
$PREFIX/include/qt/Qsci/qsciscintilla.h:2138:25: error: implicit instantiation of undefined template 'QPointer<QsciLexer>'
    QPointer<QsciLexer> lex;
                        ^
$PREFIX/include/qt/QtCore/qmetatype.h:1333:1: note: template is declared here
QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER(QT_FORWARD_DECLARE_SHARED_POINTER_TYPES_ITER)
^
$PREFIX/include/qt/QtCore/qmetatype.h:209:7: note: expanded from macro 'QT_FOR_EACH_AUTOMATIC_TEMPLATE_SMART_POINTER'
    F(QPointer)
      ^
src/gui/moc_qgscodeeditorcss.cpp:79:27: error: cannot initialize object parameter of type 'QgsCodeEditor' with an expression of type 'QgsCodeEditorCSS'
    return QgsCodeEditor::qt_metacast(_clname);
                          ^~~~~~~~~~~
src/gui/moc_qgscodeeditorcss.cpp:84:26: error: cannot initialize object parameter of type 'QgsCodeEditor' with an expression of type 'QgsCodeEditorCSS'
    _id = QgsCodeEditor::qt_metacall(_c, _id, _a);
                         ^~~~~~~~~~~
3 errors generated.
ninja: build stopped: subcommand failed.
```
</details>

### CODE REVIEW

**Comment by dschreij** [comment]
Thanks for your contribution!

> I was hoping to simply upgrade this recipe to `2.10.8` (as with the other PR), but I can't pull in a version of Qt from conda-forge that uses SIP 4.19 and the 2.10 releases require SIP 4.19.

I've been working on this upgrade too (see https://github.com/conda-forge/qscintilla2-feedstock/pull/17), but left it because there were too many problems I didn't have time to solve.

The strange thing is that the pkgs/main or anaconda channels do provide a newer version of Qt (5.9.7) than conda-forge (5.6.2), with the accompanying newer sip version. I don't know why conda-forge does not update Qt anymore, but I remember it had something to do with Windows compatibility.
It's really difficult to build QScintilla with dependencies from both channels, so I hope the conda-forge crew decides to update Qt packages on their channel too sometime soon.

**Comment by dschreij** [comment]
@conda-forge/core, there are so many CI scripts now. The traditional ones pass for this build, but 3 newly added ones fail. Do they all need to pass before merging this commit into the master branch, or are some checks experimental?

**Comment by ceholden** [comment]
My commit 6426e21 doesn't actually do anything -- the tests fail on Azure because `find` is interpreted as the *nix file search program, and not the batch one. Test passes on both AppVeyor and my local test VM and I'm not immediately sure how we'd be able to make it work in both environments.

For providers it looks like we can force one or the other in the `conda-forge.yml` using the [provider](http://conda-forge.org/docs/maintainer/conda_forge_yml.html?highlight=provider#provider) field. Elsewhere it mentions Azure is default on Linux and OSX, which are both passing there. I tried rerendering with `win: appveyor` set explicitly but none of my files were modified, and the `azure-pipelines-win.yml` is set not to upload packages (on all platforms, too). Not exactly sure what will happen though

**Comment by isuruf** [comment]
You can ignore windows on azure

**Comment by dschreij** [comment]
So this can be merged?

**Comment by ceholden** [comment]
@dschreij I think so! Thanks for your attention to this, and feel free to ping me when the conda-forge Qt stack updates (I think 5.12 is next) and we can update to a newer version of QScintilla that won't need the patch (fwiw the changes in your PR were still good when I tried latest release).

**Pull request merged**
