### PR TITLE
Create Qt5 version

### PR DESCRIPTION
**Pull request by gillins**
This PR creates a Qt5 version of `qscintilla2` necessary for new versions of `qgis` etc.

### CODE REVIEW

**Comment by dschreij** [comment]
I had the Qt5 build script working a while ago (https://github.com/conda-forge/qscintilla2-feedstock/tree/qt5), but I have had no instructions from the anaconda team on how to best integrate this on forge while keeping both Qt4 and 5 versions available. I assume the Qt4 pacakges should remain available too, so by merging this PR the build scripts for Qt4 will be lost. @conda-forge-admin, what is the best way to go at this? I raised this as an [issue](https://github.com/conda-forge/qscintilla2-feedstock/issues/4) on this repo a while ago, but the discussion has died since then.

**Comment by gillins** [comment]
Apparently it is not possible to have both Qt4 and Qt5 installed at once (see https://github.com/conda-forge/qt-feedstock/issues/15#issuecomment-272603134). Since Qt4 is no longer supported it seems sensible to upgrade everything to Qt5 and just have the old builds for Qt4. @ccordoba12 and @ocefpaf may have more thoughts on this.

> I had the Qt5 build script working a while ago

I hadn't seen that. Feel free to close this PR.

**Comment by dschreij** [comment]
I might as well merge your PR since it also passes the tests and my version is quite stale (I haven't tested it in quite a while).

**Comment by dschreij** [comment]
And thanks @gillins!

**Comment by ocefpaf** [comment]
> Since Qt4 is no longer supported it seems sensible to upgrade everything to Qt5 and just have the old builds for Qt4.

That is pretty much it. We should upgraded everything we can to `qt5`.

**Comment by dschreij** [comment]
@ocefpaf Is anaconda still stuck at PyQt 5.6(.2), or has the team found a way around the lack of support by Riverbank for the compilers used for the conda environment?

**Pull request merged**
