### PR TITLE
Qtmain

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

I think this might be on the right track, but not working yet.

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
@conda-forge/qscintilla2 any chance someone can give me a hand with the windows build? I think it should be modified to use `sip-build` as in `recipe/build.sh` but I don't have a local windows machine to test it out on.

**Comment by dschreij** [comment]
I usually just use the Windows CI builds to check. Or are the iteration times too long for you to wait on those?

**Comment by izahn** [comment]
Basically I suck at windows, I would be happy if someone else can take a shot at it.

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
OK I think I figured out the windows build. Ready for review @conda-forge/qscintilla2

**Review by matthiasdiener — APPROVED** [review]
LGTM, thanks!

**Comment by izahn** [comment]
It would be good to merge this, several packages need it for the qt515 migration.

**Pull request merged**
