### PR TITLE
Rebuild with CDT packages

### PR DESCRIPTION
**Pull request by dschreij**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dschreij** [comment]
@grlee77 Sadly it didn't work. It now stops with the error message:
```
conda.exceptions.ResolvePackageNotFound: 
  - libxfixes-cos6-x86_64
  - libxdamage-cos6-x86_64
  - libselinux-cos6-x86_64
  - mesa-dri-drivers-cos6-x86_64
  - libxxf86vm-cos6-x86_64
  - mesa-libgl-devel-cos6-x86_64
```

**Comment by dschreij** [comment]
@conda-forge-admin, please rerender

**Comment by dschreij** [comment]
@grlee77 @ocefpaf A rerender fixed this build, but as far as I can see, this operation has dropped support for Python 3.7 (and other versions), which defeats the purpose I guess (This PR is trying to fix https://github.com/conda-forge/qscintilla2-feedstock/pull/14)

**Comment by grlee77** [comment]
It looks like you started this PR from master instead of on top of the changes from #14. To fix that, I think you just need to cherry-pick the changes to `conda-forge.yml` from commit a98411b and then rerender again to get 3.7 support.

**Comment by dschreij** [comment]
I realised that too (d'oh!). I opened a new PR based on #14: https://github.com/conda-forge/qscintilla2-feedstock/pull/16, and I'm closing this one.

**Pull request closed without merging**
