### PR TITLE
add linux_aarch64

### PR DESCRIPTION
**Pull request by matthiasdiener**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matthiasdiener** [comment]
This is ready for review @conda-forge/qscintilla2

**Comment by matthiasdiener** [comment]
A gentle ping for review @conda-forge/qscintilla2 @conda-forge/core

**Comment by dschreij** [comment]
I am too unfamiliar on the architecture matters since I haven't worked with conda for a while. I can merge this after a very shallow review, but I don't think that's desirable

**Comment by wolfv** [comment]
Looks good to me!

**Comment by dschreij** [comment]
Thanks @matthiasdiener and @wolfv

**Pull request merged**
